### ISSUE TITLE
Detecting sticky section is applied

### ISSUE THREAD

**Issue by sepehr1313** [codecks-io/react-sticky-box#13]
Hi,
I need to call a function when the section is sticky. Is there any way to detect whenever we have a sticky section at the top/bottom of a page?

**Comment by danielberndt** [comment]
No this information is currently not exposed. But if you wan't you can try and create a PR 🙂
A good place for firing your event listener would be whenever `this.mode` is set.

**Comment by sepehr1313** [comment]
I've sent a PR. Could you please check that?

**Comment by sepehr1313** [comment]
I noticed that if the node is smaller than viewport, that will only be sticky. How can we detect the current position for those nodes?

**Comment by danielberndt** [comment]
What is it that you're trying to do?

Will something like [`react-measure`](https://github.com/souporserious/react-measure) help?
You could use it like this.

```
<Measure onResize={cb}>{measureRef=>
  <StickyBox><div ref={measureRef}>my content</div></StickBox>
}</Measure
```

But I don't know if react-measure will fire the event when you scroll. Maybe you need to create your own wrapper in that case.

**Comment by danielberndt** [comment]
Okay, I just googled for `pseudo selector sticky` and saw that it's a hotly debated issue. Here's a workaround presented by the google developers page: https://developers.google.com/web/updates/2017/09/sticky-headers

**Comment by sepehr1313** [comment]
I think we need to have some extra props such as **id** and **refs** then.

**Comment by mattpardee** [comment]
FYI I was able to accomplish this by using [react-waypoint](https://www.npmjs.com/package/react-waypoint) and something like this:

```
const [profileHeaderStuck, setProfileHeaderStuck] = useState(false);

return (
  <Waypoint
    onPositionChange={e => setProfileHeaderStuck(e.currentPosition === 'above')}
  />
  <StickyBox>
    <div className={classNames('d-flex align-items-center bg-white', {
        'border-bottom': profileHeaderStuck,
      })}
    >
```

Since the waypoint is right above the StickyBox, when waypoint's position changes from "inside" to "above" we know that the waypoint is just above the top of the browser window, so I set a state var and the inner element whose styling I want to change gets a new border. Border goes away when we scroll back down.
