### ISSUE TITLE
Allow both a top and bottom `offset` at the same time

### ISSUE THREAD

**Issue by mdingena** [codecks-io/react-sticky-box#17]
The top `offset` is useful particularly when you also have a fixed navigation bar at the top of your page, so that your sidebar isn't partially hidden underneath it when it's `sticky`.

But what if I have both a fixed top *and* bottom bar? I've got a fixed navigation at the top of my page, and a fixed footer containing a music player.

I've partically solved this by giving the `<StickyBox />` a child container with `padding-bottom: 110px;`. This makes sure that the sidebar's bottom content can be seen above the music player when the user still hasn't reached the end of the page.

But this introduces a new problem where when the user actually *does* reach the end of the page, the sidebar content starts to scroll up 110 pixels.

In an attempt to work around this, I've written a `onChangeMode` function that sets `padding-bottom: 0` when `oldMode` was `relative` and `newMode` is `stickyBottom`. This works, but it results in jumpy behavior when scrolling back up (because the padding pops back in).

On a related issue, scrolling back up seems to *always* cause a tiny jump, which seems to be equal to `offset={ 56 }` in mix case. It seems there is some kind of "deadzone" that is related to the offset that is given to StickyBox.

At any rate, it would be very helpful if it was possible to give `<StickyBox />` both a `top` and `bottom` offset, so we don't need these workarounds when dealing with fixed headers *and* footers.

**Comment by danielberndt** [comment]
Yes, a bottom offset seems like a useful thing to have! Would you like to give this a go yourself?
To give you a pointer: this is the change that was necessary to implement the `offset` prop: https://github.com/codecks-io/react-sticky-box/commit/1184f812fc58662540ef33492119472a6bb2910e
