### ISSUE TITLE
body overflow-x: hidden

### ISSUE THREAD

**Issue by endbay** [codecks-io/react-sticky-box#27]
Greetings, if i'm adding to body overflow-x: hidden, the sticky box stop working. Without it's working like a charm. 

The Sticky box is in a deep nested Flex Layout.

Any ideas?

**Comment by danielberndt** [comment]
Hm. This is a bit hard to debug but maybe this one could work:

```
body {
  overflow-x: hidden;
  overflow-y: auto;
}
```

**Comment by endbay** [comment]
Thanks for the response, but sadly no. The only way it works is with:

`
{
     overflow-x: inherit;
     overflow-y: inherit;
}
`

Tested with newest Safari/Chrome on Mac and Chrome on Windows.

**Comment by danielberndt** [comment]
Ah I see! Thanks for the example.

Unfortunately there's no way to automatically do the "right" thing if there are fixed elements on the screen. 

I see two options: 
- either you specify an `offsetTop` prop to the stickyBox with an appropriate value
- or you create a sticky header like this: https://codesandbox.io/s/k05lp4n427

**Comment by endbay** [comment]
We already using `offsetTop` because of the fixed header. But the issue is the same. But if we add `overflow-x: hidden` after it got rendered with chrome developer console it's working. 

So maybe, before rendering the the sticky box, remove all overflows in body first and after it's rendering is completed, add `overflow-x` again to the body. May this could work?

**Comment by danielberndt** [comment]
Okay I just had a closer look and I think I understood the problem. Your code sample actually exposes some interesting bugs in react-sticky-box I haven't seen yet. 

As a work-around can you maybe see if you can apply the overflow property not to `body` but a child element e.g. `#root`?

**Comment by endbay** [comment]
It's not working on #root as well. But the the error behaviour is difference.

On body it's sticks fixed and on #root it sticks relative.

**Comment by danielberndt** [comment]
Alright, I'm now trying to set up a test case containing your code. Let's see what I'll get out of it 🙂

**Comment by danielberndt** [comment]
Cool, I think I found it!
If you update to version 0.7.6 the issue should be gone:
https://codesandbox.io/s/l5yn4o8o8q

**Comment by endbay** [comment]
Great! I've updated it and added `overflow-x: hidden` again to body. Now it's working! Great Job. Solved 👍

**Comment by marcocianetti** [comment]
Hi there!

Here just to help others with my same problem.

I had:

```
html, body {
 ...
  overflow-x: hidden;
  overflow-y: auto;
}
```

And it wasn't working, so I ended up here by searching in the issues.

The problem was the `html` style; removing the `overflow` part from there, and leaving only to the `body` element made it working.

Maybe it could be useful to add it to the docs.

Hoping it helps 👋🏻
