### ISSUE TITLE
Top offset isn't recalculated when content height has been changed

### ISSUE THREAD

**Issue by unyieldingman** [codecks-io/react-sticky-box#28]
Hello! I found a strange behavior when using Sticky Box in my project. When you scroll down, the sticky gets `position: relative` and some `top` offset. After that I changed the content height. But the top offset was the same and sticky is partly out of parent.

Here is an [example](https://codesandbox.io/s/q98pozl3v4): scroll down the page, expand details, scroll down the page again and then collapse details. Result: the green border is out of black.

**Comment by danielberndt** [comment]
Thanks, good catch! I'm optimistic that I'll find some time in the next week to have a closer look.

**Comment by danielberndt** [comment]
Alright!
I just released v0.7.7 that should solve the issue: https://codesandbox.io/s/4x04r8vz84
