### ISSUE TITLE
onChangeMode is invalid

### ISSUE THREAD

**Issue by Oscar-ren** [codecks-io/react-sticky-box#29]
Hi, I found the `onChangeMode` event only trigger once when the component is mount.
![image](https://user-images.githubusercontent.com/9464221/50203394-5194d280-039c-11e9-8961-f180249d1982.png)
the element style is always position:sticky, is there anything wrong with me ? thanks

**Comment by danielberndt** [comment]
Hi,
it's a bit hard to tell what's really going on without seeing how the component is being used.
But my first guess is that the StickyBox takes up the full height of the parent container.
The issue is explained in more detail at the troubleshooting section of the docs [here](https://react-sticky-box.codecks.io).

**Comment by Oscar-ren** [comment]
yes, I fount the reason, my stickyBox has a small height, the nodeHeight + offsetTop is always less than viewHeight, so the mode will not change.
Here is the [code](https://github.com/codecks-io/react-sticky-box/blob/master/src/index.js#L188)

**Comment by danielberndt** [comment]
Okay, thanks for clarifying.

So to me it seems like everything works as expected. Or do you feel like there is an issue with the current behaviour?

**Comment by Oscar-ren** [comment]
This repository seems like to resolve if the sticky box is tall than wrapper,  and if the box is lower，the box behavior as `position:sticky`.
My Intention is to know if the box is in the overflow wrapper, when the sticky box become sticky, and then the box not sticky, so I will find the other repository to resolve my problem. thanks.
