### ISSUE TITLE
Sticky box not working in IE

### ISSUE THREAD

**Issue by Olivr3** [codecks-io/react-sticky-box#30]
Hi,

It appears that the sticky box is not working in IE.

```
const StickyViewport = styled(StickyBox)
  display: flex;
  flex-direction: column;

  @media ${breakpoints.md}, ${breakpoints.lg} {
    height: 100vh;
  }
```

```
<StickyViewport>
    <ActivitiesStats activities={activities} examDate={examDate} getColor={getColor} />
    {(hasExamStats || hasQbankStats) && (
      <React.Fragment>
        <HSeparator />
        <GroupContainer>
          {hasExamStats && (
            <FlexItem grow={1}>
              <ExamStats exam={exam} getColor={getColor} />
            </FlexItem>
          )}
          {hasExamStats && hasQbankStats && <VSeparator />}
          {hasQbankStats && (
            <FlexItem grow={1}>
              <QbankStats qbank={qbank} getColor={getColor} />
            </FlexItem>
          )}
        </GroupContainer>
      </React.Fragment>
    )}
  </StickyViewport>

```
IE does not support sticky position. 

![screenshot_2](https://user-images.githubusercontent.com/20702895/50454004-a0161400-093c-11e9-804c-bb45b2d629a2.png)

Is this a known bug?

Thanks!

**Comment by danielberndt** [comment]
Hi there,

yes, it's a known... let's call it "compromise".
In the [docs](https://react-sticky-box.codecks.io/#how-it-works) it is mentioned that StickyBox relies on `position: sticky` and falls back to a `position: relative` behaviours on browsers that do not support it.

**Comment by Olivr3** [comment]
gotcha, is there an alternative for it? 

thanks danielberndt

**Comment by danielberndt** [comment]
Unfortunately I'm not aware of any react based solution that is doing both, supporting IE as well as being responsive if the sticky container is bigger than the viewport.

One alternative I could offer is to look at the 0.5 versions of this library which emulates sticky behaviout with `position: fixed`. Check out the [changelog](https://react-sticky-box.codecks.io/changelog) for some more details for this version!

**Comment by Olivr3** [comment]
yeah, I understand. 

I tried that but no luck. 

![screenshot_3](https://user-images.githubusercontent.com/20702895/50479196-372aac80-09cd-11e9-9fe7-e203c1a59e72.png)

I will try to find a workaround somehow.

**Comment by Olivr3** [comment]
I solved the issue using `@media all and (-ms-high-contrast: none), (-ms-high-contrast: active)...`

Thanks!

```
const StickyViewport = styled(StickyBox)`
  display: flex;
  flex-direction: column;

  @media ${breakpoints.md}, ${breakpoints.lg} {
    height: 100vh;
  }

  @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    /* IE10+ CSS styles go here */
    position: fixed;
    top: 50px;
    bottom: 25px;
    left: 26px;
    right: 0;
    width: 48.5%;
    overflow-y: scroll;
    overflow-x: hidden;
  }
`
```

**Comment by danielberndt** [comment]
Ah yes! This looks like a neat little trick!
