### ISSUE TITLE
Clarification needed for browser support

### ISSUE THREAD

**Issue by ostenning** [codecks-io/react-sticky-box#32]
The documentation is a little unclear about if this library will work as desired on browsers like IE. 
It states that: 

```
For all browsers without sticky support it falls back to a position: relative behaviour which should be a decent enough fallback in most cases.
```

This is slightly misleading as the definition of `decent` is subjective. Additionally it could be interpreted that this library falls back to `position: relative;` whilst also using a JavaScript implementation of the sticky effect as other libraries use.

Thanks

**Comment by danielberndt** [comment]
Hey, thanks for your Feedback. I adjusted the section. I hope this makes the scope of this project clearer.
