### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kevinlaw91** [codecks-io/react-sticky-box#33]
Please add a license so that we can use this awesome lib. Thanks

**Comment by danielberndt** [comment]
Hi!

The `package.json` claims that this package has a ISC License. It's also visible on [the npm page](https://www.npmjs.com/package/react-sticky-box).

But I think that it probably would be wise to add an extra `LICENSE` file to make this more obvious!

**Comment by danielberndt** [comment]
LICENSE file was just added
