### ISSUE TITLE
Allow offsets in units other than pixels

### ISSUE THREAD

**Issue by arel** [codecks-io/react-sticky-box#35]
Thanks for your work on this library! I would love to be able to specify `offsetTop` or `offsetBottom` in units other than pixels. As far as I can tell the offsets must be given as unit-less numbers (i.e. in pixels). I am trying to match another element in the page whose height is in `em` units (e.g., `3.25rem`).

It would be nice if offsets could be specified in any CSS measurement unit.

**Comment by danielberndt** [comment]
having had some time to think to about it:
it would require quite a bit of code to make sure arbitrary units are supported (especially when thinking about stuff like `calc(10% + 3vh)`)
To keep this library focused I'd prefer to have these type of calculations done on the user side.

Happy to add it though if there's a straight forward way to convert these properties into pixels!
