### ISSUE TITLE
Allow user to set a custom container element of the sticky box 

### ISSUE THREAD

**Issue by jancama2** [codecks-io/react-sticky-box#45]
Right now you use `<div>` element as a container of the sticky box. 

In a lot of cases the  sticky box is a sidebar of a page and  should be represented by `<aside>` element.

API could be: 
```
<StickyBox as="aside" />
```
or something similar with `as` prop being by default `<div>`.

**Comment by danielberndt** [comment]
v1.0.0 was just released which allows using a hook to apply the StickyBox behaviour to any element.
