### ISSUE TITLE
handleScroll() null this object

### ISSUE THREAD

**Issue by craigatproperly** [codecks-io/react-sticky-box#47]
Situation: 

We recently incorporated this library, and our monitoring system (rollbar) began firing with issues like the this: 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/36340630/74275019-1e6c7b80-4ce1-11ea-8b60-6d123ad51d4d.png">

Our current hypothesis is that the scroll listener is fired after the object is already garbage collected, i.e. this is called after the object is removed: https://github.com/codecks-io/react-sticky-box/blob/master/src/index.js#L243 

Expected: 

(Assuming the listener is the issue) the listener would be removed before the object is cleaned up 

Actual: 

(Appears) the listener is not cleaned up. 

Note: 

Happy to open a PR for you to consider that adds the componentWillUnmount lifecycle method if that would be useful.  The proposed change would be something like: 

```
diff --git a/src/index.js b/src/index.js
index fb08721..5a095ec 100644
--- a/src/index.js
+++ b/src/index.js
@@ -57,6 +57,10 @@ export default class StickyBox extends React.Component {
     }
   }
 
+  componentWillUnmount(){
+    this.registerContainerRef(null);
+  }
+
   registerContainerRef = n => {
     if (!stickyProp) return;
     this.node = n;

```

**Comment by adrienlamotte** [comment]
Same issue here ! It happens after the route change (so the StickyBox in not on the page anymore), and I try to resize the page.

**Comment by ivanhu5** [comment]
Same issue here.

**Comment by mshatikhin** [comment]
Same issue here. Fix please(

**Comment by danielberndt** [comment]
Interesting to see this happening so often as I haven't observed it even though StickyBoxes are created in Codecks left and right.

So I just pushed some changes to make sure that removing event listeners happens on the correct nodes. Release should be live in a bit!

**Comment by danielberndt** [comment]
v0.9.3 released. Please let me now if it improves the situation!

**Comment by craigatproperly** [comment]
That worked to eliminate the error in our staging site test. Thanks!  

(perhaps the codecks sticky boxes were staying on screen for most sessions? )

**Comment by danielberndt** [comment]
Alright, thanks for the feedback!
