### ISSUE TITLE
StickyBox data attributes should be transfers to created div container

### ISSUE THREAD

**Issue by sunsetninja** [codecks-io/react-sticky-box#49]
Hi! Thank you for your project.
Can you please add data attributes transfer to StickyBox element?
For example, if you want to set `data-testid` on created by StickyBox div container probably the most intuitive way to do this is set it like this ```<StickyBox data-testid="some-testid" />```.
But now you have to create another inner div element for this and add to it some css.

**Comment by danielberndt** [comment]
v1.0.0 was just released which allows using a hook to apply the StickyBox behaviour to any element.
