### ISSUE TITLE
Sticky element position issue with dynamic pages

### ISSUE THREAD

**Issue by anetecima** [codecks-io/react-sticky-box#53]
Hi, I use StickyBox to display filters for filtering the my page content. there is a case when StickyBox gets stuck outside it's container. 
here is a sandbox for recreating this issue https://codesandbox.io/s/cool-darkness-hswks?file=/src/App.js

how to recreate: 
1: scroll to footer
2: scroll up until both top and bottom edges of Stickybox are outside the screen.
3. press "remove" button to change page content
4. scroll up and down to see how it's stuck.

**Comment by danielberndt** [comment]
v2.0.0 was just released which should address these types of issues.
