### ISSUE TITLE
Using with SSR

### ISSUE THREAD

**Issue by koss-lebedev** [codecks-io/react-sticky-box#6]
Hey,

first of all, thank you for making this component!

My question is, did you think about making this component work in server-side rendered apps? It breaks there because `window` object is not available, so I was thinking if we just added `window && `  to this line `if (window.CSS && window.CSS.supports) {` it would work? What do you think? I can create a PR for that

**Comment by danielberndt** [comment]
Good point! I just fixed it, I believe it should now work. Have a look at v0.6.2!
