### ISSUE TITLE
Allow passing in custom `getScrollParent`

### ISSUE THREAD

**Issue by danielj41** [codecks-io/react-sticky-box#7]
Problem
---

`getScrollParent` isn't working correctly for my particular use case:

* My scroll container (`overflow-y`) is outside of my React app.
* My React app isn't mounted in the DOM yet when `getScrollParent` runs.

(We're including the React app inside of a page written in a legacy framework. This problem occurs because of how we mount the React section of the page.)

Minimal working example
---

Fork of main example: https://codesandbox.io/s/x2kkkrjm8q 

The relevant changes are:

* Move `.content-container` out of `<Page>` and into `index.html`.
* Render `<Page>` into a div that isn't in the DOM yet.

```js
const div = document.createElement("div");
ReactDOM.render(<Page />, div);

const scrollContainer = document.querySelector(".content-container");
scrollContainer.appendChild(div);
```

Suggested solution
---

This is a pretty specific edge case that probably isn't worth supporting in this library. That said, I'd like the ability to pass in a custom `getScrollParent` implementation. Then I could do:

```jsx
<StickyBox getScrollParent={() => document.getElementById('#scroll-container')}>
```

**Comment by danielberndt** [comment]
The current way of identifying the scroll container doesn't rely on the scroll container to be created by react:

https://github.com/codecks-io/react-sticky-box/blob/67600d1ed56dfc5432c1f10a9738367457c36278/src/index.js#L4-L11

Once a StickyBox is mounted it uses its node's native `.offsetParent` to find the scroll container.
So if the current implementation does not identify the correct scroll parent in your case, it might be that there's a more general error that's worth fixing!

**Comment by danielberndt** [comment]
Okay, makes sense.
Two workarounds. 
Only mount StickyBox after `scrollContainer.appendChild`.

You could use a component like this:

```js
class DelayedMount extends Component {
  this.state = {mountChildren: false}
  componentDidMount() {
    setTimeout(() => this.setStat({mountChildren: true}))
  }
  render() {
    return this.state.mountChildren ? this.props.children : null
  }
}
```

Or you do something like this:

```js
class Page extends React.Component {

  handleRef = (n) => {
    this.stickyBoxInstance = n;
  }

  onPageProperlyMounted = () => {
    // call this function to simulate unmounting and re-mounting the underlying node.

    this.stickyBoxInstance.registerContainerRef(null);
    this.stickyBoxInstance.registerContainerRef(this.stickyBoxInstance.node);
  }

  render() {
    return (
      <div>
        <StickyBox ref={this.handleRef}>
          {...contents}
        </StickyBox>
      </div>
    );
  }
}
```

**Comment by danielj41** [comment]
Nice, thank you for sharing workarounds! I tried the first one and it works for us. I'm happy to close this issue as `won't fix`.

**Comment by danielberndt** [comment]
Alright :)
