### ISSUE TITLE
'StickyBox' only refers to to a type

### ISSUE THREAD

**Issue by DecliningLotus** [codecks-io/react-sticky-box#74]
I'm using TypeScript 4.5 and Next.js 12 for this.

`import StickyBox from "react-sticky-box";` using StickyBox as a component returns the following TypeScript error: 
`'StickyBox' only refers to a type, but is being used as a value here.` 

It works perfectly fine in my development environment, but once I go to production where type checking occurs in CI, the type checker will fail due to that error. My editor picks that up too.

This is probably a misconfiguration in the package for exporting the dist files which bundles fine, but confuses the type checker.

My current workaround is just using an `@ts-ignore` comment to skip type checking for that line.

**Comment by tzarger** [comment]
Or downgrade to 0.9.3. This issue is with the recently released 1.0.0

**Comment by dan-lee** [comment]
I've submitted a PR here: #75 

You can use [`patch-package`](https://github.com/ds300/patch-package) with [the patch](https://patch-diff.githubusercontent.com/raw/codecks-io/react-sticky-box/pull/75.patch) until it's resolved

**Comment by danielberndt** [comment]
v1.0.1 was just released with fixed types. Thanks for reporting it!
