### ISSUE TITLE
1.0.1 does not work with react scripts 4.X

### ISSUE THREAD

**Issue by repoit** [codecks-io/react-sticky-box#78]
React-sticky-box 1.0.1 works fine when using react scripts 5.X

```
[...]
"react-scripts": "^5.0.0",
"react-sticky-box": "^1.0.1",
[...]
```

However, when using 4.X for **react-scripts** the import of **react-sticky-box** fails
```
[...]
"react-scripts": "^4.0.3",
"react-sticky-box": "^1.0.1",
[...]
```

`import StickyBox from "react-sticky-box";`

`Module not found: Can't resolve 'react-sticky-box'`

Any idea on how to resolve this issue? Upgrading to **react-scripts** is not really an option as it introduced major code breaks to many depending libraries.

**Comment by danielberndt** [comment]
I assume it's due to being offered as an ESM module? Haven't looked into how react-scripts support those.

In that case 0.9.3 should still work fine. The api is pretty much the same, it just lacks the hook.

**Comment by danielberndt** [comment]
Merging #77 could possibly have helped. Can you check whether 1.0.2 works for you?

**Comment by repoit** [comment]
@danielberndt Upgrading to 1.0.2 fixed the issue. Thank you.
