### ISSUE TITLE
change value of top: 0px

### ISSUE THREAD

**Issue by budiybudiy** [codecks-io/react-sticky-box#8]
I need to make space from div header to StickyBox , i try to add style to <StickyBox style={{top:75}} but  it doesn't work.  i hope you will fix this. Thank you!

**Comment by danielberndt** [comment]
Hello!
Have you seen [this issue](https://github.com/codecks-io/react-sticky-box/issues/5)? Are there potentially some take aways that might help you? (e.g. creating a wrapper with padding around sticky-box)

**Comment by budiybudiy** [comment]
hi, thank you for quick response. 
but creating a wrapper with padding around sticky-box only make space between 2 boxs before scroll, this what i am going to do,

before scroll,
![before](https://user-images.githubusercontent.com/7077571/39794385-3e28f1a0-5374-11e8-81ac-762a17aa681e.jpg)

after scroll right now is stick to header
![after scroll - now](https://user-images.githubusercontent.com/7077571/39794591-457cb1b6-5375-11e8-9944-8b12d8246874.jpg)


what i want,
![after scroll - i want](https://user-images.githubusercontent.com/7077571/39794598-4f256154-5375-11e8-907f-43750e5a9558.jpg)


it will be nice if i can change value css of top:0 to top: 75px

**Comment by danielberndt** [comment]
There's a whole lot of calculations involved which make it hard to allow setting the `top` value from the outside.

I'd suggest to create a wrapper around StickyBox like this:

```jsx
<div style={{padding: "75px 0"}}>
  <StickyBox>{...content...}</StickyBox>
</div>
```

**Comment by saorabhkr** [comment]
@danielberndt putting a extra div with padding doesn't solve the problem reason it will put same extra space from top. look at this example. 

https://codesandbox.io/s/w64l83450l

**Comment by danielberndt** [comment]
Thanks for the sample. I just rewrote it to make it work: https://codesandbox.io/s/jj48zj9yow

**Comment by saorabhkr** [comment]
Perfect, but the problem with this sample is you missed the alignment. Can I make it configurable and send a PR to you so you can review and publish.

**Comment by danielberndt** [comment]
v0.6.3 was just released adding offset support!
