### ISSUE TITLE
Position is not recalculated on height change when in sticky mode

### ISSUE THREAD

**Issue by Sprinter100** [codecks-io/react-sticky-box#96]
Hi! I've encountered a little problem.

Here's an example https://codesandbox.io/s/intelligent-brook-jq2xkp?file=/src/App.js

Try scrolling to the bottom of the sidebar (so that is becomes "sticky") and then click on the expand buttons.

**Expected behavior:** The sidebar that is sticky becomes relatively positioned and it's now possible to scroll down to the **new** bottom of the sidebar

**Actual behavior:**
	1. It's not possible to scroll the sidebar further down to see the new content. 
	2. When you start scrolling the page iup, the sidebar snaps to the new bottom.

The same thing happens when the sidebar's height decreases. Try collapsing the expanded blocks when the sidebar is scrolled to its bottom and is "position: sticky"

**Comment by danielberndt** [comment]
Hi @Sprinter100, thanks for the report.

I've just updated the sticky box to v2.0.5 which seems to resolve the issue: https://codesandbox.io/s/smoosh-leftpad-465vj6

Feel free to reopen if the error still occurs on your end!
